feat: Release drafts (#3)

diff --git a/.github/workflows/wrangler.yaml b/.github/workflows/wrangler.yaml
--- a/.github/workflows/wrangler.yaml
+++ b/.github/workflows/wrangler.yaml
@@ -9,12 +9,10 @@
 name: Wrangler
 
 on:
-
   # Automatically run anytime there
   # is a push to the default branch
   push:
     branches:
-      - $default-branch
       - trunk
 
   # Automatically run anytime a PR
@@ -22,7 +20,6 @@ on:
   # for the defined types.
   pull_request:
     branches:
-      - $default-branch
       - trunk
     types:
       - opened
@@ -31,12 +28,6 @@ on:
       - ready_for_review
       - review_requested
 
-  # Re-build every week to ensure
-  # the site still builds as external
-  # dependencies change.
-  schedule:
-    - cron: '0 0 * * 0'
-
 permissions:
   contents: read
   pull-requests: write
@@ -44,27 +35,23 @@ permissions:
   statuses: read
 
 defaults:
-
   run:
     shell: bash
 
 env:
+  HUGO_VERSION: 0.111.3
 
-  HUGO_VERSION: 0.110.0
+  WRANGLER_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_TOKEN }}
 
-  WRANGLER_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS }}
-
-  # Works on pushes or PRs
-  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
+  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
+  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}
 
 jobs:
-
   ##################################################
   # Publish to Cloudflare Workers using the Wrangler CLI
   ##################################################
 
   deploy:
-
     name: Publish website
 
     runs-on: ${{ matrix.os }}
@@ -78,7 +65,6 @@ jobs:
           - ubuntu-latest
 
     steps:
-
       - id: checkout_repository
         name: Checkout repository with submodules
         uses: actions/checkout@v3
@@ -100,16 +86,31 @@ jobs:
         run: |
           rm -f themes/*/content/post/* || echo "Failed to remove posts from theme"
           rm -f themes/*/data/authors/* || echo "Failed to remove authors from theme"
+          rm -rf assets/images/backup || echo "Failed to remove extra images"
           rm -rf static/images/backup || echo "Failed to remove extra images"
 
+      - id: hugo_modules
+        name: Download Hugo modules
+        run: |
+          if [[ -f package.json ]]; then
+            echo "Running npm install"
+            npm install
+          fi
+          if [[ -f "go.mod" ]]; then
+            echo "Downloading Go modules"
+            go mod download -x
+          else
+            echo "No go.mod file found"
+          fi
+          echo "Downloading Hugo modules"
+          hugo mod clean
+          hugo mod tidy
+          hugo mod graph
+
+      # Any branch other than the default is staged for preview.
       - id: hugo_build_staging
         name: Build the website using Hugo (Staging)
-        if: |
-          startsWith( env.BRANCH_NAME, 'draft/' ) ||
-          startsWith( env.BRANCH_NAME, 'bug/' ) ||
-          startsWith( env.BRANCH_NAME, 'fix/' ) ||
-          startsWith( env.BRANCH_NAME, 'feat/' ) ||
-          github.event_name == 'pull_request'
+        if: env.BRANCH_NAME_CURRENT != env.BRANCH_NAME_DEFAULT
         env:
           TZ: "Australia/Sydney"
         run: |
@@ -117,9 +118,9 @@ jobs:
           touch public/.nojekyll
           ls -la public/
 
+      # The default branch is 'Production'
       - id: hugo_build_production
-        if: |
-          env.BRANCH_NAME == 'trunk'
+        if: env.BRANCH_NAME_CURRENT == env.BRANCH_NAME_DEFAULT
         name: Build the website using Hugo (Production)
         env:
           TZ: "Australia/Sydney"
@@ -128,11 +129,10 @@ jobs:
           touch public/.nojekyll
           ls -la public/
 
-      # Only 'draft/*' branches are pushed to the Staging website
       - id: publish_website_staging
         name: Publish website using Wrangler (Staging)
         if: |
-          startsWith( env.BRANCH_NAME, 'draft/' ) &&
+          env.BRANCH_NAME_CURRENT != env.BRANCH_NAME_DEFAULT &&
           steps.hugo_build_staging.outcome == 'success'
         uses: cloudflare/wrangler-action@2.0.0
         with:
@@ -146,7 +146,7 @@ jobs:
       - id: publish_website_production
         name: Publish website using Wrangler (Production)
         if: |
-          env.BRANCH_NAME == 'trunk' &&
+          env.BRANCH_NAME_CURRENT == env.BRANCH_NAME_DEFAULT &&
           steps.hugo_build_production.outcome == 'success'
         uses: cloudflare/wrangler-action@2.0.0
         with:
@@ -161,7 +161,6 @@ jobs:
   ##################################################
 
   check:
-
     name: PR Status Checks
 
     runs-on: ${{ matrix.os }}
@@ -177,7 +176,6 @@ jobs:
     needs: deploy
 
     steps:
-
       - name: PR Status Giphy
         id: pr-status-giphy
         uses: dgteixeira/pr-status-giphy-action@v2
